version: '3.7'

services:
  php_fpm:
    build: ./docker/php-fpm
    volumes:
      - ./:/srv/app:rw,cached
      - /srv/app/var/

  nginx:
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./public:/srv/app/public:ro
    depends_on:
      - php_fpm
    ports:
      - 80:80

  # This HTTP/2 proxy is not secure: it should only be used in dev
#  h2-proxy:
#    build: ./docker/h2-proxy
#    depends_on:
#      - nginx
#    volumes:
#      - ./docker/h2-proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
#    ports:
#      - 443:443

  node:
    image: node:12-alpine
    user: "node"
    command: tail -f /dev/null
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    ports:
        - 3000:3000
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
